# Playbook is to Rollback the current working build to the previous version
# This playbook will run for the role mentioned and create the symlink to the previous config

- name: Rollback DPOP
  serial: 1
  hosts: "{{group}}"
  become_user: root
  become: true
  become_method: sudo
  user: "{{user}}"
  vars_files:
          - vars/system_vars.yml 
  pre_tasks:
          - import_tasks: pre-tasks/main.yml

  roles:
          - "{{role}}"
  
