service_dir: "/opt/wapp"
master_dir: "nginx"

#Dynamic Variables
copy_config: "{{copy_config}}"
rollback: "{{rollback}}"
currert_version: "{{current_version}}"
previous_version: "{{previous_version}}"

