- stat:
        path: "{{service_dir}}/{{master_dir}}"
  register: sym

- stat:
        path: "{{service_dir}}/{{previous_version}}"
  register: oldnginx

- name: Check if the directory match
  set_fact:
        installed_version: '{{sym.stat.lnk_source | basename| replace("/opt/wapp/", "")}}'
        latest_version: '{{current_version}}'
        rollback_version: '{{previous_version}}'

- block:
        - name: "Exit playbook if no rollback version available."
          debug: 
            msg: "Don't have a previous rollback version available"
            
        - meta: end_play
          when: (oldnginx.stat.exists and oldnginx.stat.isdir) or (installed_version == rollback_version)
