- name: Nginx config test
  become: yes
  command: "{{item}}"
  with_items:
          - cd {{service_dir}} && sudo chown -R cfgadmin:cfgadmin {{service_dir}}/{{master_dir}}
          - cp -f  {{service_dir}}/{{master_dir}}/conf/nginx.conf /tmp/nginx.conf
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/master_dirlications {{service_dir}}/{{master_dir}}/conf/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/certs {{service_dir}}/{{master_dir}}/conf/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/rules {{service_dir}}/{{master_dir}}/conf/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/infra {{service_dir}}/{{master_dir}}/conf/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/partner {{service_dir}}/{{master_dir}}/conf/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/modsecurity {{service_dir}}/{{master_dir}}/conf/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/idp/master_dirs {{service_dir}}/{{master_dir}}/conf/idp/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/idp/customization {{service_dir}}/{{master_dir}}/conf/idp/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/idp/kerberos {{service_dir}}/{{master_dir}}/conf/idp/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/idp/saml {{service_dir}}/{{master_dir}}/conf/idp/.
          - cp -f  {{service_dir}}/{{previous_version}}/conf/dialin_exception_peers.conf {{service_dir}}/{{master_dir}}/conf/
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/dialin-master_dirlications {{service_dir}}/{{master_dir}}/conf/.
          - cp -rf  {{service_dir}}/{{previous_version}}/conf/ocsps {{service_dir}}/{{master_dir}}/conf/.

