- name: Nginx config changes
  block:
          - include_tasks: check_nginx.yml
          - include_tasks: reload_nginx.yml
          - include_tasks: create_symlink.yml
            when: (role == "cloud_proxy") and (rollback == "true")


