#- name: Pointing back to old nginx folder
# shell: cd {{service_dir}} && ln -sfn {{new_nginx_build}} {{new_folder}}
# shell: cd {{service_dir}} && sudo chown -R cfgadmin:cfgadmin {{service_dir}}/{{new_folder}}

- stat:
        path: "{{service_dir}}/{{master_dir}}"
  register: sym

- name: Check if the directory match
  set_fact:
        installed_version: '{{sym.stat.lnk_source | basename| replace("/opt/wapp/", "")}}'
        latest_version: '{{current_version}}'
        rollback_version: '{{previous_version}}'

- block:
        - name: "Exit playbook if no rollback version available."
          debug: 
            msg: "Don't have a previous rollback version available"
            
        - meta: end_play
          when: installed_version == rollback_version

- name: create a symlink
  become: yes
  become_user: cfgadmin
  file:
           src: "{{rollback_version}}"
           dest: "{{service_dir}}/{{master_dir}}"
           state: link
           #when: installed_version == latest_version

- name: reloading nginx
  block: 
        - include_role: name=nginx
